### ISSUE TITLE
Inconsistent Filter size

### ISSUE THREAD

**Issue by Ranim-94** [Ranim-94/Stage_Cense_2020#2]
the Log_Main_Encoder_Part contains an issue regarding the convolution size output. Don't know if there is a mistake in the implementation or no.

**Comment by felixgontier** [comment]
Can you please post a full error log including the lines?
It seems that you reimplemented the network as it is described, but the input representation in our case is significantly smaller. You may need to drop layers or reduce strides.

**Comment by Ranim-94** [comment]
Problem Solved.
